kind: pipeline
type: docker
name: default

steps:
  - name: build-openapi-map
    image: plugins/docker
    settings:
      repo: mejlholm/openapi-map
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password
      dockerfile: Dockerfile.graalvm
      tags:
        - latest
        - 0.0.${DRONE_BUILD_NUMBER}

trigger:
  branch:
    - master
  event:
    - push
---

kind: pipeline
type: docker
name: default-build-only

steps:
  - name: build-openapi-map
    image: plugins/docker
    settings:
      repo: mejlholm/openapi-map
      dry_run: true
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password
      dockerfile: Dockerfile.graalvm

trigger:
  exclude:
    branch:
      - master
  include:
    event:
    - pull_request
