---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openapi-map
  namespace: apps

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openapi-map
  namespace: apps
rules:
  - apiGroups: ["", "extensions"]
    resources: ["pods", "services", "ingresses"]
    verbs: ["list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openapi-map
  namespace: apps
roleRef:
  kind: Role
  name: openapi-map
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: openapi-map
    namespace: apps
